#version: '3.4'
#
#networks: 
#  signalrchat-network:
#    driver: bridge
#
#services:
#  signalrchat.api:
#    image: ${DOCKER_REGISTRY-}signalrchatapi
#    build:
#      context: .
#      dockerfile: Dockerfile
#    networks:
#      - signalrchat-network
#    depends_on:
#      - sql.database
#
#  sql.database:
#    container_name: signalrchat.database
#    image: microsoft/mssql-server-linux:2017-latest
#    networks:
#      - signalrchat-network